name: .NET
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/checkout@v3
      with:
        dotnet-version: 6.0.x
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USUARIO }}
        password: ${{ secrets.FTP_SENHA }}
        remote_dir: "/www/api"
        local-dir: "./Release/"


    - name: Upload ftp
      uses: genietim/ftp-action@releases/v4
      with:
        host: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "Release/"
        remoteDir: "www/api/"
